### ISSUE TITLE
files collection

### ISSUE THREAD

**Issue by Ferdi** [mitodl/ocw-studio#155]
* This config file does not pass validation but it should 

```
collections:
  - name: somesettings
    label: Some settings
    category: tag1
    files:
      - label: Default settings
        name: defaultsettings
        file: config/defaultsettings.yml
        fields:
          - label: "Some Label"
            name: "somelabel"
            widget: "string"
```

and so should this 

```
collections:
  - name: somesettings
    label: Some settings
    category: tag1
    files:
      - label: Default settings
        name: defaultsettings
        file: config/defaultsettings.yml
        fields:
          - label: "Some Label"
            name: "somelabel"
            widget: "string"
      - label: GA settings
        name: gasettings
        file: config/gasettings.yml
        fields:
          - label: "GA code"
            name: "gacode"
            widget: "string"
```

* But this one should not

```
collections:
  - name: somesettings
    label: Some settings
    category: tag1
    file: config/defaultsettings.yml
    fields:
      - label: "Some Label"
        name: "somelabel"
        widget: "string"
```

####  Description

There are only 2 types of collections *folder* or *files*  (not *file*)
*files* type collections contain one ore more files (defaultsettings and gasettings above)
