### ISSUE TITLE
The field named "body" should be treated as markdown

### ISSUE THREAD

**Issue by Ferdi** [mitodl/ocw-studio#157]
### Steps to Reproduce

Use a config file like this one 

```
collections:
  - name: "blog" 
    label: "Blog" 
    folder: "content/blog"
    category: tag1
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  
```

Create a blog post 

![Screen Shot 2021-03-25 at 10 58 09 PM](https://user-images.githubusercontent.com/125561/112571048-9995d180-8dbd-11eb-947a-f55b719ea259.png)

### Expected Behavior

The content of the "body" field should be saved in the "markdwon" field in the database

### Actual Behavior

It get saved in the "metadata" field

![Screen Shot 2021-03-25 at 10 59 43 PM](https://user-images.githubusercontent.com/125561/112571143-d06be780-8dbd-11eb-9325-f2a767b7be38.png)

We should treat "body" as as special field that means "content"
