### ISSUE TITLE
Menu YAML for some legacy courses has both url and pageRef

### ISSUE THREAD

**Issue by pt2302** [mitodl/ocw-studio#1856]
In https://github.com/mitodl/ocw-studio/pull/1845, the `url` property was replaced with `pageRef` for internal menu items. However, for legacy data that stores both `url` and `identifier` fields, updating the menu will now result in the YAML having both `url` and `pageRef`, as below:

```
leftnav:
- identifier: c9b592be-0215-c31f-6f65-02243f2987bb
  name: Syllabus
  pageRef: /pages/syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 66c5c691-0366-d451-4ec6-011d0e9ba305
  name: Calendar
  pageRef: /pages/calendar
  url: /pages/calendar
  weight: 20
- identifier: 12a1aaf9-be7a-ca1d-756d-c7f978d7513c
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  url: /pages/lecture-notes
  weight: 30
- identifier: 59d10fc0-a31a-74c3-07d0-42b79008c871
  name: Assignments
  pageRef: /pages/assignments
  url: /pages/assignments
  weight: 40
```

(from https://github.mit.edu/ocw-content-rc/16.333-fall-2004/blob/main/config/_default/menus.yaml)
