### ISSUE TITLE
Add support for filtering collection members in Relation widget

### ISSUE THREAD

**Issue by aliceriot** [mitodl/ocw-studio#289]
When I'm linking to items in another collection with the Relation widget, I'd like to be able to define a filter which will constrain the list in some way.

For instance, I'd like to limit links to a `Resource` collection to only those entries which have `filetype: "PDF"`.

Here's an example `.yml` file showing how this can look:

```yml
collections:
  - name: page
    label: Page
    category: Content
    folder: content
    fields:
      - {
        "label": "PDFs",
        "name": "pdfs",
        "widget": "relation",
        "collection": "resource",
        "display_field": "name",
        "multiple": true,
        "max": 10,
        "min": 1,
        "filter": { field: "filetype", equals: "PDF"}
        }

  - name: resource
    label: Resource
    category: Content
    folder: content
    fields:
      - {"label": "Title", "name": "title", "widget": "string", "required": true}
      - {"label": "Description", "name": "description", "widget": "text"}
      - {"label": "File", "name": "file", "widget": "file"}
      - {
        "label": "File Type",
        "default": [ "PDF" ],
        "name": "filetype",
        "options": [ "PDF", "Word Doc", "PPT" ],
        "widget": "select"
        }
```

#### Acceptance Criteria:

- [ ] Add support for setting a 'filter'  property on the `Relation` widget which can, for now, define a `field` to check and an `equals` property for the values we're going to require on those entries
- [ ] Change the backend API to allow optionally returning full data in the content listing API, so we can get those fields in our request and be able to compare their values
- [ ] filter the entries in the linked-to collection before we pass them to the `Select` widget (i.e. show them in the UI)
