### ISSUE TITLE
Implement "label_singular"  option for collection

### ISSUE THREAD

**Issue by Ferdi** [mitodl/ocw-studio#324]
Studio uses the collection label in different contexts. Sometimes is necessary to know both singular and plural version of the label

![ocw_studio_promo](https://user-images.githubusercontent.com/125561/122150900-95150e00-ce2c-11eb-9bd2-3afef3513cf2.png)

Add label_singular options : 

```
collections: 
  - name: 'promos' 
    label: 'Promos' # Used in the UI
    label_singular: 'Promo' # Used in the UI, ie: "New Promo"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: 'content/promos'

```
