### ISSUE TITLE
validation gets blocked by required fields in hidden objects

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#337]
### Steps to Reproduce

 - Create a `WebsiteStarter` configuration that has the following configuration:
```
  - category: Content
    folder: content/resources
    label: Resources
    name: resource
    fields:
      - label: Title
        name: title
        required: true
        widget: string
      - label: Description
        name: description
        widget: markdown
        minimal: true
      - label: File Type
        name: filetype
        required: true
        widget: select
        options:
          - Image
          - Video
          - Document
          - Other
      - label: File
        name: file
        widget: file

      # show the field below only if the type of resource is "image"
      - label: Image Metadata
        name: metadata
        widget: object
        condition: { field: filetype, equals: Image }
        fields:
          - label: Text alternative
            name: image-alt
            widget: string
            required: true
          - label: Caption
            name: caption
            widget: string
          - label: Credit
            name: credit
            widget: text
```
 - Create a new `Website` using the `WebsiteStarter` you just created
 - Browse to the UI to edit this site, and bring up the form to add a new Resource
 - Select a `filetype` other than Image
 - Try and save the resource

### Expected Behavior

The resource saves using the supplied settings

### Actual Behavior

It does not save and does not indicate why it did not save
