### ISSUE TITLE
Relation widget:  Add "ordered" option

### ISSUE THREAD

**Issue by Ferdi** [mitodl/ocw-studio#687]
We need support collections ( in studio config) like video gallery , or  image gallery . Currently we can do something like this

```
collections:
  - category: Content
    folder: content/videolectures
    label: Video Gallery
    name: videogallery
    fields:
      - label: Title
        name: title
        widget: string
        required: true

      - label: Body
        name: body
        widget: markdown

      - label: Videos
         name: gallery_videos
         widget: relation
         collection: resource
         display_field: title
         multiple: true
         filter:
            field: "resourcetype"
            filter_type: "equals"
            value: "Vidoe"
```

This would be ok, it's not ideal. It would be hard to arrange the order of videos in the gallery.  

The suggestion here is to add a new attribute `sortable` to the relation widget. If `true`,  The relation widget UI would looks something like :
![videogallery](https://user-images.githubusercontent.com/125561/137067723-16e5bfae-2d0f-47e7-9f38-eeb9c3f21b76.png)
